var quotes = [
    "Design is intelligience made visible.",
    "Design is so simple. That's why it's so complicated.",
    "If a design is taking too long, the design is wrong.",
    "If you think good design is expensive, you should take a look at the cost of bad design.",
    "Design simplifies complications.",
    "Design is where science & art break even.",
    "Design is thinking made visual.",
    "Imagination is the beginning of creation.",
    "Creativity is intelligence having fun.",
    "Creativity is allowing yourself to make mistakes. Design is knowing which ones to keep.",
    "You can't use up creativity. The more you use, the more you have.",
    "Design adds value faster than it adds costs.",
    "The public is more familiar with bad design than good design. It is, in effect, conditioned to prefer bad design, because that is what it lives with. The new becomes threatening, the old reassuring.",
    "Designers are meant to be loved, not to be understood.",
    "Make it simple, but significant.",
    "Every great design begins with an even better story.",
    "Design creates culture. Culture shapes values. Values determine the future.",
    "The function of design is letting design function.",
    "Design is not just what it looks like and feels like. Design is how it works.",
    "Design is not a single object or dimension. Design is messy and complex.",
    "Design is the intermediary between information and understanding.",
    "A designer knows he has achieved perfection not when there is nothing left to add, but when there is nothing left to take away.",
    "Design is a formal response to a strategic question.",
    "Styles come and go. Good design is a language, not a style.",
    "Design can be art. Design can be aesthetics. Design is so simple, that's why it is so complicated.",
    "It's through mistakes that you actually can grow. You have to get bad in order to get good.",
    "Accessible design is good design.",
    "Where you innovate, how you innovate, and what you innovate are design problems.",
    "I strive for two things in design: simplicity and clarity. Great design is born of those two things.",
    "Design is as much an act of spacing as an act of marking."
];